-- utility file to clear out default SSU data from srichenb_cs355fa22 database

USE srichenb_cs355fa22;

DROP TABLE IF EXISTS BK_Prereq;
DROP TABLE IF EXISTS BK_Time_slot;
DROP TABLE IF EXISTS BK_Advisor;
DROP TABLE IF EXISTS BK_Takes;
DROP TABLE IF EXISTS BK_Student;
DROP TABLE IF EXISTS BK_Teaches;
DROP TABLE IF EXISTS BK_Section;
DROP TABLE IF EXISTS BK_Instructor;
DROP TABLE IF EXISTS BK_Course;
DROP TABLE IF EXISTS BK_Department;
DROP TABLE IF EXISTS BK_Classroom;
DROP TABLE IF EXISTS SSU_Takes;
DROP TABLE IF EXISTS SSU_Student;
DROP TABLE IF EXISTS SSU_Teaches;
DROP TABLE IF EXISTS SSU_Section;
DROP TABLE IF EXISTS SSU_Instructor;
DROP TABLE IF EXISTS SSU_Course;
DROP TABLE IF EXISTS SSU_Department;
DROP TABLE IF EXISTS SSU_Classroom;